repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^fpdf_mod\/|\.(min\.css|min\.js|po|mo|txt)$
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^fpdf_mod\/
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort
        exclude: ^fpdf_mod\/
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        exclude: ^fpdf_mod\/
