repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(min\.css|min\.js|po|mo|txt|svg)$|(staticfiles/vendor\/)
      - id: end-of-file-fixer
        exclude: \.(min\.css|min\.js|po|mo|txt|svg)$|(staticfiles/vendor\/)
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
