cache:
  directories:
  - $HOME/.cache/pre-commit
language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install pre-commit codecov
  - pip install -e ".[testing]"
script:
  - pre-commit run --all-files
  - coverage run -m unittest
notifications:
  email: false
after_success:
  - codecov
