cache:
  directories:
  - $HOME/.cache/pre-commit
language: python
python:
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install pre-commit codecov PyPDF2 coverage
  - pip install -e .
script:
  - pre-commit run --all-files
  - coverage run -m unittest
notifications:
  email: false
after_success:
  - codecov
