cache:
  directories:
  - $HOME/.cache/pre-commit
language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
install:
 - pip install pre-commit tox
script:
  - pre-commit run --all-files
  - tox
notifications:
  email: false
